export const generalMessageConstant = {
    notLengthComments: 'Ще не добавлено жодного коментаря, станьте першими хто залишить коментарій!',
    updateNickName: 'Будь ласка напишіть ваш новий псевдонім',
    updatePassword: 'Будь ласка напишіть ваш новий пароль',
    updateEmail: 'Будь ласка напишіть ваш новий email',
    updateConfirmPassword: 'Будь ласка підвердіть ваш новий пароль',
    currentPassword: 'Будь ласка напишіть ваш поточний пароль для збереження змін',
    successfullyUserUpdate: 'Зміни були успішно збережені!',
    successfullyRegistration: 'Вас було успішно зареєстровано!',
    adminCreateBook: 'Створити книгу',
    adminUpdateBook: 'Оновити книгу',
    adminUpdateAuthor: 'Оновити автора',
    adminCreateAuthor: 'Створити автора',
    adminCreateGenre: 'Створити жанр',
    adminDeleteGenre: 'Видалити жанр',
    required: 'Обов`язково',
    adminCreatedBook: 'Книгу було успішно створено.',
    adminUpdatedBook: 'Книгу було успішно оновлено.',
    adminUpdatedAuthor: 'Автора було успішно оновлено.',
    adminPartialCreatedBook: 'Книгу було успішно створено, проте файли не були добавлені.',
    adminCreatedAuthor: 'Автора було успішно створено.',
    adminPartialCreatedAuthor: 'Автора було успішно створено, проте картинка не була добавлена.',
    adminCreatedGenre: 'Новий жанр було створено.',
    adminDeletedGenre: 'Жанр було успішно виделано.',
    analyticsToDay: 'Аналітика за сьогодні',
    analyticsToWeek: 'Аналітика за цей тиждень',
    analyticsToMonth: 'Аналітика за цей місяць',
    analyticsToAll: 'Аналітика за весь час',
};
