export const queryConstant = {
    sortBy: 'sortBy',
    page: 'page',
    perPage: 'perPage',
    commentsPage: 'commentsPage',
    commentsPerPage: 'commentsPerPage',
    updateRemove: 'updateRemove',
    updateSet: 'updateSet',
    noveltyPage: 'noveltyPage',
    noveltyPerPage: 'noveltyPerPage',
    ratingsPage: 'ratingsPage',
    ratingsPerPage: 'ratingsPerPage',
    genresPerPage: 'genresPerPage',
    genresPage: 'genresPage',
    search: 's',
    forgot: 'forgot',
    clientKey: 'clientKey',
    date: 'date',
};
