export const routePathConstant = {
    authors: 'authors',
    authorSinglePage: 'authors/:id',
    bookSinglePage: 'books/:id',
    readTextFilePage: 'books/:id/read-online/:fileName',
    alreadyReadsPage: 'profile/already-reads',
    willReadsPage: 'profile/will-reads',
    favoritesPage: 'profile/favorites',
    settingsPage: 'profile/settings',
    logoutPage: '/',
    novelty: '/novelty',
    books: '/books',
    ratings: 'ratings',
    genres: 'genres',
    genresPage: 'genres/:genre',
    search: 'search',
    forgotPassword: 'forgotPassword',
    admin: '/admin',
    adminAnalytics: '/admin/analytics',
    adminBookEdit: 'admin/book-edit/:id',
    adminAuthorEdit: 'admin/author-edit/:id',
    adminBookEditWithoutId: '/admin/book-edit',
    adminAuthorEditWithoutId: '/admin/author-edit',
};
