import { IUrls } from '../interfaces';

export const urls: IUrls = {
    genres: '/genres',
    auth: '/auth',
    registration: '/registration',
    login: '/login',
    google: '/google',
    success: '/success',
    logout: '/logout',
    refresh: '/refresh',
    authors: '/authors',
    books: '/books',
    views: '/views',
    comments: '/comments',
    alreadyRead: '/alreadyread',
    favorites: '/favorites',
    willRead: '/willRead',
    ratings: '/ratings',
    likes: '/likes',
    last: '/last',
    update: '/update',
    users: '/users',
    verify: '/verify',
    forgotPassword: '/forgotPassword',
    admin: '/admin',
    all: '/all',
    files: '/files',
};
