"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpMessageEnum = void 0;
var HttpMessageEnum;
(function (HttpMessageEnum) {
    HttpMessageEnum["CONTINUE"] = "CONTINUE";
    HttpMessageEnum["SWITCHING_PROTOCOLS"] = "SWITCHING PROTOCOLS";
    HttpMessageEnum["PROCESSING"] = "PROCESSING";
    HttpMessageEnum["EARLYHINTS"] = "EARLYHINTS";
    HttpMessageEnum["OK"] = "OK";
    HttpMessageEnum["CREATED"] = "CREATED";
    HttpMessageEnum["ACCEPTED"] = "ACCEPTED";
    HttpMessageEnum["NON_AUTHORITATIVE_INFORMATION"] = "NON AUTHORITATIVE INFORMATION";
    HttpMessageEnum["NO_CONTENT"] = "NO CONTENT";
    HttpMessageEnum["RESET_CONTENT"] = "RESET CONTENT";
    HttpMessageEnum["PARTIAL_CONTENT"] = "PARTIAL CONTENT";
    HttpMessageEnum["AMBIGUOUS"] = "AMBIGUOUS";
    HttpMessageEnum["MOVED_PERMANENTLY"] = "MOVED PERMANENTLY";
    HttpMessageEnum["FOUND"] = "FOUND";
    HttpMessageEnum["SEE_OTHER"] = "SEE OTHER";
    HttpMessageEnum["NOT_MODIFIED"] = "NOT MODIFIED";
    HttpMessageEnum["TEMPORARY_REDIRECT"] = "TEMPORARY REDIRECT";
    HttpMessageEnum["PERMANENT_REDIRECT"] = "PERMANENT REDIRECT";
    HttpMessageEnum["BAD_REQUEST"] = "BAD REQUEST";
    HttpMessageEnum["UNAUTHORIZED"] = "UNAUTHORIZED";
    HttpMessageEnum["PAYMENT_REQUIRED"] = "PAYMENT REQUIRED";
    HttpMessageEnum["FORBIDDEN"] = "FORBIDDEN";
    HttpMessageEnum["NOT_FOUND"] = "NOT FOUND";
    HttpMessageEnum["METHOD_NOT_ALLOWED"] = "METHOD NOT ALLOWED";
    HttpMessageEnum["NOT_ACCEPTABLE"] = "NOT ACCEPTABLE";
    HttpMessageEnum["PROXY_AUTHENTICATION_REQUIRED"] = "PROXY AUTHENTICATION REQUIRED";
    HttpMessageEnum["REQUEST_TIMEOUT"] = "REQUEST TIMEOUT";
    HttpMessageEnum["CONFLICT"] = "CONFLICT";
    HttpMessageEnum["GONE"] = "GONE";
    HttpMessageEnum["LENGTH_REQUIRED"] = "LENGTH REQUIRED";
    HttpMessageEnum["PRECONDITION_FAILED"] = "PRECONDITION FAILED";
    HttpMessageEnum["PAYLOAD_TOO_LARGE"] = "PAYLOAD TOO LARGE";
    HttpMessageEnum["URI_TOO_LONG"] = "URI TOO LONG";
    HttpMessageEnum["UNSUPPORTED_MEDIA_TYPE"] = "UNSUPPORTED MEDIA TYPE";
    HttpMessageEnum["REQUESTED_RANGE_NOT_SATISFIABLE"] = "REQUESTED RANGE NOT SATISFIABLE";
    HttpMessageEnum["EXPECTATION_FAILED"] = "EXPECTATION_FAILED";
    HttpMessageEnum["I_AM_A_TEAPOT"] = "I AM A TEAPOT";
    HttpMessageEnum["MISDIRECTED"] = "MISDIRECTED";
    HttpMessageEnum["UNPROCESSABLE_ENTITY"] = "UNPROCESSABLE ENTITY";
    HttpMessageEnum["FAILED_DEPENDENCY"] = "FAILED DEPENDENCY";
    HttpMessageEnum["PRECONDITION_REQUIRED"] = "PRECONDITION REQUIRED";
    HttpMessageEnum["TOO_MANY_REQUESTS"] = "TOO MANY REQUESTS";
    HttpMessageEnum["INTERNAL_SERVER_ERROR"] = "INTERNAL SERVER ERROR";
    HttpMessageEnum["NOT_IMPLEMENTED"] = "NOT IMPLEMENTED";
    HttpMessageEnum["BAD_GATEWAY"] = "BAD GATEWAY";
    HttpMessageEnum["SERVICE_UNAVAILABLE"] = "SERVICE UNAVAILABLE";
    HttpMessageEnum["GATEWAY_TIMEOUT"] = "GATEWAY TIMEOUT";
    HttpMessageEnum["HTTP_VERSION_NOT_SUPPORTED"] = "HTTP VERSION NOT SUPPORTED";
})(HttpMessageEnum = exports.HttpMessageEnum || (exports.HttpMessageEnum = {}));
//# sourceMappingURL=http-message.enum.js.map