"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpStatusEnum = void 0;
var HttpStatusEnum;
(function (HttpStatusEnum) {
    HttpStatusEnum[HttpStatusEnum["CONTINUE"] = 100] = "CONTINUE";
    HttpStatusEnum[HttpStatusEnum["SWITCHING_PROTOCOLS"] = 101] = "SWITCHING_PROTOCOLS";
    HttpStatusEnum[HttpStatusEnum["PROCESSING"] = 102] = "PROCESSING";
    HttpStatusEnum[HttpStatusEnum["EARLYHINTS"] = 103] = "EARLYHINTS";
    HttpStatusEnum[HttpStatusEnum["OK"] = 200] = "OK";
    HttpStatusEnum[HttpStatusEnum["CREATED"] = 201] = "CREATED";
    HttpStatusEnum[HttpStatusEnum["ACCEPTED"] = 202] = "ACCEPTED";
    HttpStatusEnum[HttpStatusEnum["NON_AUTHORITATIVE_INFORMATION"] = 203] = "NON_AUTHORITATIVE_INFORMATION";
    HttpStatusEnum[HttpStatusEnum["NO_CONTENT"] = 204] = "NO_CONTENT";
    HttpStatusEnum[HttpStatusEnum["RESET_CONTENT"] = 205] = "RESET_CONTENT";
    HttpStatusEnum[HttpStatusEnum["PARTIAL_CONTENT"] = 206] = "PARTIAL_CONTENT";
    HttpStatusEnum[HttpStatusEnum["AMBIGUOUS"] = 300] = "AMBIGUOUS";
    HttpStatusEnum[HttpStatusEnum["MOVED_PERMANENTLY"] = 301] = "MOVED_PERMANENTLY";
    HttpStatusEnum[HttpStatusEnum["FOUND"] = 302] = "FOUND";
    HttpStatusEnum[HttpStatusEnum["SEE_OTHER"] = 303] = "SEE_OTHER";
    HttpStatusEnum[HttpStatusEnum["NOT_MODIFIED"] = 304] = "NOT_MODIFIED";
    HttpStatusEnum[HttpStatusEnum["TEMPORARY_REDIRECT"] = 307] = "TEMPORARY_REDIRECT";
    HttpStatusEnum[HttpStatusEnum["PERMANENT_REDIRECT"] = 308] = "PERMANENT_REDIRECT";
    HttpStatusEnum[HttpStatusEnum["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    HttpStatusEnum[HttpStatusEnum["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    HttpStatusEnum[HttpStatusEnum["PAYMENT_REQUIRED"] = 402] = "PAYMENT_REQUIRED";
    HttpStatusEnum[HttpStatusEnum["FORBIDDEN"] = 403] = "FORBIDDEN";
    HttpStatusEnum[HttpStatusEnum["NOT_FOUND"] = 404] = "NOT_FOUND";
    HttpStatusEnum[HttpStatusEnum["METHOD_NOT_ALLOWED"] = 405] = "METHOD_NOT_ALLOWED";
    HttpStatusEnum[HttpStatusEnum["NOT_ACCEPTABLE"] = 406] = "NOT_ACCEPTABLE";
    HttpStatusEnum[HttpStatusEnum["PROXY_AUTHENTICATION_REQUIRED"] = 407] = "PROXY_AUTHENTICATION_REQUIRED";
    HttpStatusEnum[HttpStatusEnum["REQUEST_TIMEOUT"] = 408] = "REQUEST_TIMEOUT";
    HttpStatusEnum[HttpStatusEnum["CONFLICT"] = 409] = "CONFLICT";
    HttpStatusEnum[HttpStatusEnum["GONE"] = 410] = "GONE";
    HttpStatusEnum[HttpStatusEnum["LENGTH_REQUIRED"] = 411] = "LENGTH_REQUIRED";
    HttpStatusEnum[HttpStatusEnum["PRECONDITION_FAILED"] = 412] = "PRECONDITION_FAILED";
    HttpStatusEnum[HttpStatusEnum["PAYLOAD_TOO_LARGE"] = 413] = "PAYLOAD_TOO_LARGE";
    HttpStatusEnum[HttpStatusEnum["URI_TOO_LONG"] = 414] = "URI_TOO_LONG";
    HttpStatusEnum[HttpStatusEnum["UNSUPPORTED_MEDIA_TYPE"] = 415] = "UNSUPPORTED_MEDIA_TYPE";
    HttpStatusEnum[HttpStatusEnum["REQUESTED_RANGE_NOT_SATISFIABLE"] = 416] = "REQUESTED_RANGE_NOT_SATISFIABLE";
    HttpStatusEnum[HttpStatusEnum["EXPECTATION_FAILED"] = 417] = "EXPECTATION_FAILED";
    HttpStatusEnum[HttpStatusEnum["I_AM_A_TEAPOT"] = 418] = "I_AM_A_TEAPOT";
    HttpStatusEnum[HttpStatusEnum["MISDIRECTED"] = 421] = "MISDIRECTED";
    HttpStatusEnum[HttpStatusEnum["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY";
    HttpStatusEnum[HttpStatusEnum["FAILED_DEPENDENCY"] = 424] = "FAILED_DEPENDENCY";
    HttpStatusEnum[HttpStatusEnum["PRECONDITION_REQUIRED"] = 428] = "PRECONDITION_REQUIRED";
    HttpStatusEnum[HttpStatusEnum["TOO_MANY_REQUESTS"] = 429] = "TOO_MANY_REQUESTS";
    HttpStatusEnum[HttpStatusEnum["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
    HttpStatusEnum[HttpStatusEnum["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED";
    HttpStatusEnum[HttpStatusEnum["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
    HttpStatusEnum[HttpStatusEnum["SERVICE_UNAVAILABLE"] = 503] = "SERVICE_UNAVAILABLE";
    HttpStatusEnum[HttpStatusEnum["GATEWAY_TIMEOUT"] = 504] = "GATEWAY_TIMEOUT";
    HttpStatusEnum[HttpStatusEnum["HTTP_VERSION_NOT_SUPPORTED"] = 505] = "HTTP_VERSION_NOT_SUPPORTED";
})(HttpStatusEnum = exports.HttpStatusEnum || (exports.HttpStatusEnum = {}));
//# sourceMappingURL=http-status.enum.js.map