"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MessageEnum = void 0;
var MessageEnum;
(function (MessageEnum) {
    MessageEnum["CONTINUE"] = "CONTINUE";
    MessageEnum["SWITCHING_PROTOCOLS"] = "SWITCHING PROTOCOLS";
    MessageEnum["PROCESSING"] = "PROCESSING";
    MessageEnum["EARLYHINTS"] = "EARLYHINTS";
    MessageEnum["OK"] = "OK";
    MessageEnum["CREATED"] = "CREATED";
    MessageEnum["ACCEPTED"] = "ACCEPTED";
    MessageEnum["NON_AUTHORITATIVE_INFORMATION"] = "NON AUTHORITATIVE INFORMATION";
    MessageEnum["NO_CONTENT"] = "NO CONTENT";
    MessageEnum["RESET_CONTENT"] = "RESET CONTENT";
    MessageEnum["PARTIAL_CONTENT"] = "PARTIAL CONTENT";
    MessageEnum["AMBIGUOUS"] = "AMBIGUOUS";
    MessageEnum["MOVED_PERMANENTLY"] = "MOVED PERMANENTLY";
    MessageEnum["FOUND"] = "FOUND";
    MessageEnum["SEE_OTHER"] = "SEE OTHER";
    MessageEnum["NOT_MODIFIED"] = "NOT MODIFIED";
    MessageEnum["TEMPORARY_REDIRECT"] = "TEMPORARY REDIRECT";
    MessageEnum["PERMANENT_REDIRECT"] = "PERMANENT REDIRECT";
    MessageEnum["BAD_REQUEST"] = "BAD REQUEST";
    MessageEnum["UNAUTHORIZED"] = "UNAUTHORIZED";
    MessageEnum["PAYMENT_REQUIRED"] = "PAYMENT REQUIRED";
    MessageEnum["FORBIDDEN"] = "FORBIDDEN";
    MessageEnum["NOT_FOUND"] = "NOT FOUND";
    MessageEnum["METHOD_NOT_ALLOWED"] = "METHOD NOT ALLOWED";
    MessageEnum["NOT_ACCEPTABLE"] = "NOT ACCEPTABLE";
    MessageEnum["PROXY_AUTHENTICATION_REQUIRED"] = "PROXY AUTHENTICATION REQUIRED";
    MessageEnum["REQUEST_TIMEOUT"] = "REQUEST TIMEOUT";
    MessageEnum["CONFLICT"] = "CONFLICT";
    MessageEnum["GONE"] = "GONE";
    MessageEnum["LENGTH_REQUIRED"] = "LENGTH REQUIRED";
    MessageEnum["PRECONDITION_FAILED"] = "PRECONDITION FAILED";
    MessageEnum["PAYLOAD_TOO_LARGE"] = "PAYLOAD TOO LARGE";
    MessageEnum["URI_TOO_LONG"] = "URI TOO LONG";
    MessageEnum["UNSUPPORTED_MEDIA_TYPE"] = "UNSUPPORTED MEDIA TYPE";
    MessageEnum["REQUESTED_RANGE_NOT_SATISFIABLE"] = "REQUESTED RANGE NOT SATISFIABLE";
    MessageEnum["EXPECTATION_FAILED"] = "EXPECTATION_FAILED";
    MessageEnum["I_AM_A_TEAPOT"] = "I AM A TEAPOT";
    MessageEnum["MISDIRECTED"] = "MISDIRECTED";
    MessageEnum["UNPROCESSABLE_ENTITY"] = "UNPROCESSABLE ENTITY";
    MessageEnum["FAILED_DEPENDENCY"] = "FAILED DEPENDENCY";
    MessageEnum["PRECONDITION_REQUIRED"] = "PRECONDITION REQUIRED";
    MessageEnum["TOO_MANY_REQUESTS"] = "TOO MANY REQUESTS";
    MessageEnum["INTERNAL_SERVER_ERROR"] = "INTERNAL SERVER ERROR";
    MessageEnum["NOT_IMPLEMENTED"] = "NOT IMPLEMENTED";
    MessageEnum["BAD_GATEWAY"] = "BAD GATEWAY";
    MessageEnum["SERVICE_UNAVAILABLE"] = "SERVICE UNAVAILABLE";
    MessageEnum["GATEWAY_TIMEOUT"] = "GATEWAY TIMEOUT";
    MessageEnum["HTTP_VERSION_NOT_SUPPORTED"] = "HTTP VERSION NOT SUPPORTED";
})(MessageEnum = exports.MessageEnum || (exports.MessageEnum = {}));
//# sourceMappingURL=message.enum.js.map