"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StatusEnum = void 0;
var StatusEnum;
(function (StatusEnum) {
    StatusEnum[StatusEnum["CONTINUE"] = 100] = "CONTINUE";
    StatusEnum[StatusEnum["SWITCHING_PROTOCOLS"] = 101] = "SWITCHING_PROTOCOLS";
    StatusEnum[StatusEnum["PROCESSING"] = 102] = "PROCESSING";
    StatusEnum[StatusEnum["EARLYHINTS"] = 103] = "EARLYHINTS";
    StatusEnum[StatusEnum["OK"] = 200] = "OK";
    StatusEnum[StatusEnum["CREATED"] = 201] = "CREATED";
    StatusEnum[StatusEnum["ACCEPTED"] = 202] = "ACCEPTED";
    StatusEnum[StatusEnum["NON_AUTHORITATIVE_INFORMATION"] = 203] = "NON_AUTHORITATIVE_INFORMATION";
    StatusEnum[StatusEnum["NO_CONTENT"] = 204] = "NO_CONTENT";
    StatusEnum[StatusEnum["RESET_CONTENT"] = 205] = "RESET_CONTENT";
    StatusEnum[StatusEnum["PARTIAL_CONTENT"] = 206] = "PARTIAL_CONTENT";
    StatusEnum[StatusEnum["AMBIGUOUS"] = 300] = "AMBIGUOUS";
    StatusEnum[StatusEnum["MOVED_PERMANENTLY"] = 301] = "MOVED_PERMANENTLY";
    StatusEnum[StatusEnum["FOUND"] = 302] = "FOUND";
    StatusEnum[StatusEnum["SEE_OTHER"] = 303] = "SEE_OTHER";
    StatusEnum[StatusEnum["NOT_MODIFIED"] = 304] = "NOT_MODIFIED";
    StatusEnum[StatusEnum["TEMPORARY_REDIRECT"] = 307] = "TEMPORARY_REDIRECT";
    StatusEnum[StatusEnum["PERMANENT_REDIRECT"] = 308] = "PERMANENT_REDIRECT";
    StatusEnum[StatusEnum["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    StatusEnum[StatusEnum["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    StatusEnum[StatusEnum["PAYMENT_REQUIRED"] = 402] = "PAYMENT_REQUIRED";
    StatusEnum[StatusEnum["FORBIDDEN"] = 403] = "FORBIDDEN";
    StatusEnum[StatusEnum["NOT_FOUND"] = 404] = "NOT_FOUND";
    StatusEnum[StatusEnum["METHOD_NOT_ALLOWED"] = 405] = "METHOD_NOT_ALLOWED";
    StatusEnum[StatusEnum["NOT_ACCEPTABLE"] = 406] = "NOT_ACCEPTABLE";
    StatusEnum[StatusEnum["PROXY_AUTHENTICATION_REQUIRED"] = 407] = "PROXY_AUTHENTICATION_REQUIRED";
    StatusEnum[StatusEnum["REQUEST_TIMEOUT"] = 408] = "REQUEST_TIMEOUT";
    StatusEnum[StatusEnum["CONFLICT"] = 409] = "CONFLICT";
    StatusEnum[StatusEnum["GONE"] = 410] = "GONE";
    StatusEnum[StatusEnum["LENGTH_REQUIRED"] = 411] = "LENGTH_REQUIRED";
    StatusEnum[StatusEnum["PRECONDITION_FAILED"] = 412] = "PRECONDITION_FAILED";
    StatusEnum[StatusEnum["PAYLOAD_TOO_LARGE"] = 413] = "PAYLOAD_TOO_LARGE";
    StatusEnum[StatusEnum["URI_TOO_LONG"] = 414] = "URI_TOO_LONG";
    StatusEnum[StatusEnum["UNSUPPORTED_MEDIA_TYPE"] = 415] = "UNSUPPORTED_MEDIA_TYPE";
    StatusEnum[StatusEnum["REQUESTED_RANGE_NOT_SATISFIABLE"] = 416] = "REQUESTED_RANGE_NOT_SATISFIABLE";
    StatusEnum[StatusEnum["EXPECTATION_FAILED"] = 417] = "EXPECTATION_FAILED";
    StatusEnum[StatusEnum["I_AM_A_TEAPOT"] = 418] = "I_AM_A_TEAPOT";
    StatusEnum[StatusEnum["MISDIRECTED"] = 421] = "MISDIRECTED";
    StatusEnum[StatusEnum["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY";
    StatusEnum[StatusEnum["FAILED_DEPENDENCY"] = 424] = "FAILED_DEPENDENCY";
    StatusEnum[StatusEnum["PRECONDITION_REQUIRED"] = 428] = "PRECONDITION_REQUIRED";
    StatusEnum[StatusEnum["TOO_MANY_REQUESTS"] = 429] = "TOO_MANY_REQUESTS";
    StatusEnum[StatusEnum["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
    StatusEnum[StatusEnum["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED";
    StatusEnum[StatusEnum["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
    StatusEnum[StatusEnum["SERVICE_UNAVAILABLE"] = 503] = "SERVICE_UNAVAILABLE";
    StatusEnum[StatusEnum["GATEWAY_TIMEOUT"] = 504] = "GATEWAY_TIMEOUT";
    StatusEnum[StatusEnum["HTTP_VERSION_NOT_SUPPORTED"] = 505] = "HTTP_VERSION_NOT_SUPPORTED";
})(StatusEnum = exports.StatusEnum || (exports.StatusEnum = {}));
//# sourceMappingURL=status.enum.js.map