export interface IUrls {
    genres: string,
    auth: string,
    registration: string,
    login: string,
    google: string,
    success: string,
    logout: string,
    refresh: string,
    authors: string,
    books: string,
    views: string,
    comments: string,
    alreadyRead: string,
    favorites: string,
    willRead: string,
    ratings: string,
    likes: string,
    last: string,
    users: string,
    update: string,
    verify: string,
    admin: string,
    forgotPassword: string,
    all: string,
    files: string,
}
